"""Add status field to standard_form table

Revision ID: add_status_to_standard_form
Revises: 60f8daed10a1
Create Date: 2025-08-04 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_status_to_standard_form'
down_revision = '60f8daed10a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column to standard_form table with default value 'pending'
    op.add_column('standard_form', sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove status column from standard_form table
    op.drop_column('standard_form', 'status')
    # ### end Alembic commands ###
